import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "../components/Card";

export default function Home() {
  return (
    <>
      <Head>
        <title>QR Code Component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card
          imgSrc="/image-qr-code.png"
          imgAltText="QR Code"
          headerText="Improve your front-end skills by building projects"
          paragraphText="Scan the QR code to visit Frontend Mentor and take your coding skills to the next level"
        />
      </main>
    </>
  );
}
